databases:
  - name: safespace-db
    plan: free
    databaseName: safespace
    user: safespace
    region: frankfurt

services:
  - type: web
    name: safespace-server
    runtime: docker
    dockerfilePath: ./docker/server.Dockerfile
    dockerContext: ./server
    plan: free
    region: frankfurt
    branch: main
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: safespace-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_ISSUER_BASE_URL
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
